name: 'deploy-gh-pages'
on: 
  push:
    branches:
      - main
  pull_request:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: copy
        run: |
          files=$(find . -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git switch -c 'gh-pages'
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD || git commit -am "deploy files"
          git push origin gh-pages
          
