name: 'deploy-gh-pages'
on: 
  push:
    branches:
      - main
  pull_request:
  
jobs:
  copy_files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source_repository: [https://github.com/minova-afis/aero.minova.github.pages.git]
        source_branch: [gh-pages]
        target_branch: [gh-pages]
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Copy files another repository into the current
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.source_repository }}
          ref: ${{ matrix.source_branch }}
      - name: download files
        run: |
          cp -f ./_config.yml .
          cp -rf ./_includes .
          cp -rf ./assets .
          cp -f ./.gitignore
      - uses: actions/checkout@v3
      - name: copy
        run: |
          files=$(find . -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout gh-pages
          git checkout main -- README.md
          git checkout main -- doc
          git add -A
          git commit -m 'update README.md and /doc'
          git push origin gh-pages
